name: Deployment Workflow
on:
  push:
    branches: [ "*" ]  
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name:  Get Branch Name
      shell: bash
      run:  |
             echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV   
    
    - name: Check Out Latest Commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Get Docker Image Tag
      env:
        MAJOR_VERSION: ${{ vars.MAJOR_VERSION }}
        MINOR_VERSION: ${{ vars.MINOR_VERSION }}
      run: |
           echo "branch: $BRANCH"
           BUILD_NUMBER=$(/usr/bin/git rev-list --count HEAD $BRANCH) && echo "RELEASE_VERSION=$MAJOR_VERSION.$MINOR_VERSION.$BUILD_NUMBER" >> $GITHUB_ENV
      shell: bash

    - name: Deploy App to Server
      uses: appleboy/ssh-action@master
      env:
        APP_NAME: "${{ vars. APP_NAME }}"
        APP_PORT: "${{ vars. APP_PORT }}"
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      with:
        host: ${{ secrets.APP_SERVER_IP }}
        username: ${{ secrets.APP_SERVER_USERNAME }}
        password: ${{ secrets.APP_SERVER_PASSWORD }}
        port: ${{ vars.APP_SERVER_PORT }}
        envs: APP_NAME,REPOSITORY,APP_PORT,DOCKER_USERNAME,BRANCH,RELEASE_VERSION
        script: |
          echo '${{ secrets.APP_SERVER_PASSWORD }}'|sudo -S su -
          rm -rf /tmp/${{ github.event.repository.name }}
          cd /tmp/
          git clone --single-branch --branch $BRANCH  git@github.com-${{ github.event.repository.name }}:ExtraCareApp/${{ github.event.repository.name }}.git
          cd /tmp/${{ github.event.repository.name }}
          sudo  docker build  --build-arg PORT="$PORT" -t  $APP_NAME-$BRANCH .
          sudo docker tag $APP_NAME-$BRANCH "$DOCKER_USERNAME/$APP_NAME-$BRANCH:$RELEASE_VERSION" 
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          sudo docker push  "$DOCKER_USERNAME/$APP_NAME-$BRANCH:$RELEASE_VERSION" 
          echo '${{ secrets.APP_SERVER_PASSWORD }}'|sudo -S su -
          echo '${{ secrets.APP_SERVER_PASSWORD }}'|sudo docker rm -f ${APP_NAME}-${BRANCH}-server #&>/dev/null
          echo '${{ secrets.APP_SERVER_PASSWORD }}'|sudo -S docker run -d --name ${APP_NAME}-${BRANCH}-server --restart=always --privileged -e PORT=$APP_PORT -p ${APP_PORT}:${APP_PORT}  $DOCKER_USERNAME/$APP_NAME-$BRANCH:$RELEASE_VERSION
          rm -rf /tmp/${{ github.event.repository.name }}
   